export const booksOfTheBible = [
	"Gen:Genesis",
	"Ex:Exodus",
	"Lev:Leviticus",
	"Num:Numbers",
	"Deut:Deuteronomy",
	"Josh:Joshua",
	"Judg:Judges",
    "Ruth:Ruth",
    "1 Sam:1%20Samuel",
    "2 Sam:2%20Samuel",
    "1 King:1%20Kings",
    "2 King:2%20Kings",
    "1 Chr:1%20Chronicles",
    "2 Chr:2%20Chronicles",
    "Ezra:Ezra",
    "Neh:Nehemiah",
    "Esth:Esther",
    "Job:Job",
    "Ps:Psalms",
    "Prov:Proverbs",
    "Eccl:Ecclesiastes",
    "Sol:Song%20of%20Solomon",
    "Isa:Isaiah",
    "Jer:Jeremiah",
    "Lam:Lamentations",
    "Ezek:Ezekiel",
    "Dan:Daniel",
    "Hos:Hosea",
    "Joel:Joel",
    "Amos:Amos",
    "Obad:Obadiah",
    "Jon:Jonah",
    "Mic:Micah",
    "Nah:Nahum",
    "Hab:Habakkuk",
    "Zep:Zephaniah",
    "Hag:Haggai",
    "Zech:Zechariah",
    "Mal:Malachi",
    "Mat:Matthew",
    "Mark:Mark",
    "Luke:Luke",
    "John:John",
    "Act:The%20Acts",
    "Rom:Romans",
    "1 Cor:1%20Corinthians",
    "2 Cor:2%20Corinthians",
    "Gal:Galatians",
    "Eph:Ephesians",
    "Phil:Philemon",
    "Col:Colossians",
    "1 Th:1%20Thessalonians",
    "2 Th:2%20Thessalonians",
    "1 Tim:1%20Timothy",
    "2 Tim:2%20Timothy",
    "Tit:Titus",
    "Phn:Philemon",
    "Heb:Hebrews",
    "Jam:James",
    "1 Pet:1%20Peter",
    "2 Pet:2%20Peter",
    "1 John:1%20John",
    "2 John:2%20John",
    "3 John:3%20John",
    "Jud:Judah",
    "Rev:Revelation",
];
